brian.lynn_auth0_606245e5d39a5a00700d27bc-CollateralInterestContribution
finos/common-domain-model pull request #1893
Opened 2023-01-23 14:25 UTC by regnosys-prod-user

2023-03-07 18:47 UTC, tomhealey-icma approved these changes

2023-03-07 18:50 UTC, tomhealey-icma commented
As these changes are limited to the csa and isda-create I have no requested changes but I would suggest avoid using attribute names that include specific domain references, 

enum AlternativeToInterestAmountEnum: <"If there is an alternative to interest amounts, how is it done?">
    CSA_Standard   <" TBD ">
    CSA_NonStandard   <" TBD ">
    Not_Applicable  <" TBD ">

It would be better to not include CSA in the attribute but if necessary use a Source Attribute /ENUM reference.

2023-03-15 12:28 UTC, minesh-s-patel commented
/easycla

2023-03-22 09:17 UTC, lolabeis requested changes

2023-03-22 09:17 UTC, lolabeis commented on rosetta-source/src/main/rosetta/mapping-isdacreate-synonym.rosetta
I see that we are removing ISDA Create synonyms for `DistributionAndInterestPayment`, which makes sense given that we are replacing this type with a new structure. We should address the following questions:

- Do we know what document type(s) will be affected, and does the Collateral WG mind?
- What about CreateIQ and its users?
- If users do mind, do all the attributes that we were mapping to in the old structure have a target in the new one?

Based on the answer to those questions, we can formulate a plan. An interim delivery would maintain both the old and new types in parallel, and also maintain all the synonyms for the former, while marking the old type as `deprecated`. In a second step, we would remap ISDA Create attributes to the new type and then retire the old.

2023-03-22 09:17 UTC, lolabeis commented on rosetta-source/src/main/rosetta/legaldocumentation-csa-type.rosetta
> +type DistributionAndInterestPaymentOld: <"A class to specify the Distributions and Interest Payment provisions applicable to the Japanese Law ISDA 2016 CSA for Initial Margin and the New York Law ISD
See comment re synonyms

2023-03-22 09:17 UTC, lolabeis commented on rosetta-source/src/main/rosetta/legaldocumentation-csa-type.rosetta
>  	interestRate EligibleCurrencyInterestRate (1..*) <"The interest rate associated with initial or variation margin collateral, depending upon the type of credit agreement that this election is associa
There are other types to be deprecated, that are only used as attributes in this type:

- `EligibleCurrencyInterestRate`
- `InterestAmount`
- `InterestAdjustment`

2023-03-27 17:15 UTC, iansloyan commented
A redesign is to be proposed by @brianlynn2 - I think it is appropriate to close this PR now

2023-03-27 17:15 UTC, closed without merging