Task 5015: Addition of Clearing Receipt Date Time in EventTimestampQualificationEnum in CDM
finos/common-domain-model pull request #2060
Opened 2023-03-21 16:29 UTC by hugohills-regnosys

2023-03-22 16:59 UTC, tomhealey-icma requested changes
I question the use of enumerations for the purpose of qualify event workflow timestamps. In this specific case, the presence of a clearing event receipt and its timestamp should be sufficient. Already there's a growing list a workflow specific timestamp enums that appear to be duplicative if the event also exists.

2023-03-24 12:34 UTC, tomhealey-icma commented
I still have a concern over expanding lists of enumerations to define events. In this scenario, there should be clearly defined events for each step in the workflow that would include date and timestamp.

2023-03-24 22:58 UTC, hugohills-regnosys commented
Thanks @tomhealey-icma.  Yes, agreed on both points.  

I have raised two corresponding issues:
- https://github.com/finos/common-domain-model/issues/2072 - Enums should be in UpperCamelCase
- https://github.com/finos/common-domain-model/issues/2073 - Review EventTimestampQualificationEnum

We could discuss briefly on Monday if you have time.

2023-03-28 11:56 UTC, tomhealey-icma approved these changes

2023-03-28 13:30 UTC, merged