Adding the FinalPrincipalExchangeCalculation
finos/common-domain-model pull request #2127
Opened 2023-04-28 10:28 UTC by minesh-s-patel

Adding the FinalPrincipalExchangeCalculation for inflation swaps. Added the finalPrincipalExchangeCalculation field with a type of FinalPrincipalExchangeCalculation. Also added a field underneath FinalPrincipalExchangeCalculation which is of type Boolean. This is per the FpML data model, CDM was not supporting this.

2023-05-12 18:46 UTC, ben-aubry commented
Hi Team, any blockers to have this merged ? Let me know if there are any questions.

2023-05-23 13:21 UTC, iansloyan requested changes
I see no need for these calculations to be inflation specific. Please make generic and I will approve.

2023-05-23 13:21 UTC, iansloyan commented on rosetta-source/src/main/rosetta/product-asset-type.rosetta
Can this finalPrincipalExchangeCalculation be changed to be more generic? i.e. just remove mention of inflation swap in the comments?

2023-05-23 14:57 UTC, iansloyan commented on rosetta-source/src/main/rosetta/product-asset-type.rosetta
Following further discussion with maintainers and to preserve future extensions - could we change the boolean to be a new _PrincipalExchangeCalculationEnum_ enum with initial values you need such as "floored" "non-floored" or something along those lines? with relevant explanation?

2023-05-23 15:24 UTC, tomhealey-icma requested changes
Please change type and add Enum.

2023-07-19 18:09 UTC, ben-aubry commented
@iansloyan @tomhealey-icma, the changes were addressed, can you please approve this ?

2023-07-19 18:12 UTC, ben-aubry commented
Also, @iansloyan @tomhealey-icma, would my changes carry over to version 5.0.0 ?

2023-08-21 11:51 UTC, dshoneisda commented
@ben-aubry can this please be closed if #2314 replaces it

2023-08-23 07:31 UTC, closed without merging