Add settlement party and role to settlement base
finos/common-domain-model pull request #2214
Opened 2023-06-23 18:17 UTC by tomhealey-icma

The is model change will deprecate settlementcenterenum and add settlement party and party role. Reference, [2213](https://github.com/finos/common-domain-model/issues/2213).

2023-06-30 14:44 UTC, chrisisla requested changes
I think this change makes a lot of sense. 
Looking at the rosetta file there is a comment just below this change of "//ICMA-P2", can this be removed as well please?
There is also a very large [docReference] next to the "settlementCurrency" just above this change. I know we decided to use [docReference] to _reference_ external text and not include big swathes of text in the model. While we're in this file could we reduce the amount of text in this [docReference]?

2023-06-30 16:21 UTC, tomhealey-icma commented
I can remove the //ICMA-P2 comment and change the doc reference to:
[docReference ICMA GMRA namingConvention "Contractual Currency" provision "As defined in GMRA paragraph 2(k)/ paragraph 7(a)"]

2023-07-21 08:38 UTC, chrisisla approved these changes

2023-07-21 15:38 UTC, lolabeis commented
I do agree with the driver and purpose of the change, however it should be implemented differently.

The Party should not feature "in hard" in Settlement Terms, which is a low-level object inside Trade. Instead, the SettlementCenter should be added as an enum value in AncillaryRoleEnum. Then the actual Party entity should be specified in the Trade's list of Parties, and then tied to that enum value in the ancillaryParty attribute of TradableProduct.

Please see `ExerciseNotice` type for a template implementation.

Also could you articulate your plan for actual deletion of the existing attribute (whih you're simply marking as `deprecated`)? Existing ingested samples where this attribute is populated will need to be remapped to the new structure.

2023-08-18 17:58 UTC, merged