Vineet Kumar Story2500_ValuationModelinCDM
finos/common-domain-model pull request #2263
Opened 2023-07-13 15:20 UTC by regnosys-prod-user

2023-07-13 15:52 UTC, winitall01 commented
@hugohills-regnosys, @lolabeis - Is it possiblefor you review this PR please?

2023-07-13 17:09 UTC, lolabeis requested changes

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/observable-asset-type.rosetta
> +	valuationMethod ValuationTypeEnum (0..1) <"The ISDA defined methodology for determining the final price of the reference obligation for purposes of cash settlement. (ISDA 2003 Term: Valuation Method
Given that the term 'valuation method' is used in other places in this context (starting with the type name: `ValuationMethod`), there could be quite a hurdle to clear for changing the name.

Consequently, I would opt for the path of least resistance and change the name of the new type to `ValuationTypeEnum`

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-enum.rosetta
> +enum ValuationMethodEnum: <"Source and method used for the valuation of the transaction by the reporting counterparty.">
Change the term 'reporting counterparty' in the description to 'valuation party' (we don't want to pin this to a reporting context)

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-enum.rosetta
> +    CentralCounterpartyValuation <"Central Counterparty's Valuation">
Just `CentralCounterparty`, no `Valuation`(implied by the enum context)

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +type TradeValuation: <"Defines as the value of an investment, asset, or security">
Typo in the description: 'defines as...'

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +    datetime zonedDateTime (1..1) <"Date and time of the last valuation marked to market, provided by the central counterparty (CCP) or calculated using the current or last available market price of
`timestamp` for the attribute name rather than `datetime`

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +    method ValuationMethodEnum (1..1) <"Source and method used for the valuation of the transaction by the reporting counterparty.">
Ditto as above, change reference to 'reporting counterparty' to 'valuation party' instead.

2023-07-13 17:09 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +    delta number (0..1) <"The ratio of the change in the price of a derivative transaction to the change in the price of the underlying. This field is applicable only to options and swaptions. Update
Remove the last sentence in the description, as it's regulatory-specific

2023-07-14 17:58 UTC, tomhealey-icma requested changes
Can you explain why you include CentralCounterparty as an valuation type? Doesn't see to align with MTM. 

Why is the new type called TradeValuation and not just Valuation. Where is the link or reference to a trade if it only applies to a trade?

2023-07-16 20:53 UTC, winitall01 commented
> Can you explain why you include CentralCounterparty as an valuation type? Doesn't see to align with MTM.
> 
> Why is the new type called TradeValuation and not just Valuation. Where is the link or reference to a trade if it only applies to a trade?

1. "Central Counterparty Valuation" is one of the required types of Valuation in CFTC, EMIR and CDEs. This is why it is added in the ValuationMethodEnum. 

2. There's already an object named "Valuation" in cdm > product > asset > type. Hence TradeValuation is used. The object is included in TradeState as valuationHistory.

2023-07-17 18:12 UTC, tomhealey-icma commented
Based on your response I would say that the existing Valuation type, which looks to be just some booleans should be changed and the new type TradeValuation should not just add Trade because Valuation already exists. If it's just the valuation of a trade it should have a reference to the trade. 

Regarding the enums, if these enums are just required for regulatory reporting they should sit in the regulatory name space and use a type modifier, like CFTCValuationEnum. Central Counterparty Valuation is just a reference to the source since they will most likely use Mark-to-Market. So the other option is to add ValuationSource.

2023-07-19 12:27 UTC, lolabeis requested changes

2023-07-19 12:27 UTC, lolabeis commented on rosetta-source/src/main/rosetta/product-asset-type.rosetta
> +	valuation ValuationTerms (1..1) <"Contains all non-date valuation information.">
Also change attribute name to `valuationTerms`

2023-07-19 12:27 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +    source ValuationSourceEnum (1..1) <"Source of the valuation of the transaction by the valuation party.">
Both `method` and `source` should be (0..1) because of the `required choice` rule

2023-07-19 12:27 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +    condition ValuationType:
Add a description to the condition to explain why they're mutually exclusive

2023-07-19 15:07 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +import cdm.event.common.*
Why do you need that import? It's referencing the same namespace

2023-07-19 15:07 UTC, lolabeis commented on rosetta-source/src/main/rosetta/event-common-type.rosetta
> +        required choice method, source
cant --> cannot (avoid casual language / abbreviation)

2023-07-19 15:10 UTC, lolabeis commented
@tomhealey-icma Thanks vm for your recent review.
The PR has now been revised in accordance with your suggestions, please kindly re-approve.

2023-07-19 17:54 UTC, tomhealey-icma submitted a review, later dismissed
Reviewed with Leo and resolved questions. Discussed and agreed the future need to add riskfactors as a new type to include delta, theta, gamma, etc. The delta in valuation would eventually be deprecated.

2023-07-20 08:12 UTC, lolabeis submitted a review, later dismissed

2023-07-20 16:42 UTC, lolabeis commented
Closing as superseded by: https://github.com/finos/common-domain-model/pull/2279#pullrequestreview-1539601141

2023-07-20 16:42 UTC, closed without merging