Bataller García Eric Natural Person - Circular reference fix
finos/common-domain-model pull request #2546
Opened 2023-11-23 16:49 UTC by JayasriR

The NaturalPerson type contains a NaturalPersonRole, which references back to the containing type of NaturalPerson, causing a circular reference in the model. This issue is fixed with this contribution.

2023-11-23 17:04 UTC, JayasriR commented
Original PR: https://github.com/finos/common-domain-model/pull/2545

2023-11-23 17:05 UTC, JayasriR commented
@finos-admin

Please add the following labels to this PR:
Category: Modelling
Complexity: Minor Change
Criticality: Medium/Low
Target: Production

2023-11-24 09:00 UTC, lolabeis requested changes
This PR contains a backward-incompatible change (removal of an attribute) so should be rolled into the next dev version of CDM. I have labelled it with `Target: Development`.

Also backward incompatible changes are now required to be specifically documented in the release notes - See #2443

In the meantime, to indicate that an attribute is meant to be retired and should not be used in the prod version without breaking backward compatibility, please use the `[deprecated]` annotation instead.

2023-12-05 10:53 UTC, lolabeis submitted a review, later dismissed

2023-12-06 16:31 UTC, eacunaISDA approved these changes

2023-12-06 16:59 UTC, hugohills-regnosys approved these changes

2023-12-06 17:00 UTC, merged