Update fpml scheme import additive only 5xx
finos/common-domain-model pull request #2931
Opened 2024-05-23 08:31 UTC by PayalKhanna

2024-05-23 17:23 UTC, ja6a-regnosys requested changes

2024-05-23 17:23 UTC, ja6a-regnosys commented on pom.xml
delete both the `repositories` and `pluginRepositories` blocks

2024-05-24 10:22 UTC, hugohills-regnosys commented on RELEASE.md
> +- `rosetta-bundle` 11.6.2:
- `rosetta-bundle` 11.6.2: Dependencies migrated to Maven Central
- `rosetta-bundle` 11.7.0: Java compilation performance improvements

2024-05-24 13:19 UTC, eacunaISDA approved these changes

2024-05-24 14:48 UTC, hugohills-regnosys commented on tests/src/test/java/com/regnosys/schemaimport/SchemeImporterTest.java
>  package com.regnosys.schemaimport;
package should be `com.regnosys.schemeimport`

2024-05-24 14:53 UTC, hugohills-regnosys approved these changes

2024-05-24 15:03 UTC, merged