Website Updates
finos/common-domain-model pull request #3054
Opened 2024-07-18 19:18 UTC by eteridvalishvili

CDM Website Update - July 

- [x] Fix DPBE link
- [x] Update Overview Deck
- [x] Update the overview page with the two pointer links, a pointer to the cdm interest form
- [x] Update Governance.mp and Release.md with Brians changes
- [x] Create a materials page
- [x] Move cdm resources over from the FINOS landing page

Materials page: 

- [x] https://www.finextra.com/pressarticle/100503/six-major-banks-trial-fragmos-chain-in-otc-derivatives-market
- [x] https://www.securitiesfinancetimes.com/sltimes/SFT_issue_324.pdf
- [x] Landing Page Publications
- [x] Updated resources

Pointers to these links:

- [x] [https://www.isda.org/isda-digital-regulatory-reporting/](https://www.isda.org/2023/04/04/drr-infohub/)
- [x] https://www.isda.org/2023/02/16/isda-collateral-initiatives/
- [x] https://www.finos.org/common-domain-model
- [x] https://resources.finos.org/category/projects-sigs/common-domain-model-cdm?projects-sigs=common-domain-model-cdm&c=cG9zdDo5OTEwNzc%3D

2024-07-19 08:18 UTC, Oblongs commented on docs/CDM-Collateral-WG.md
The name of the guide is "Get Started with the CDM for Collateral" and should be used consistently.

2024-07-19 08:23 UTC, chrisisla requested changes
Can you check all the names are spelt correctly please? I have highlighted a few but there could be more.

2024-07-19 08:23 UTC, chrisisla commented on docs/cdm-materials.md
> +At the keynote session of the 2022 Open Source in Finance Forum New York, a panel of industry leaders including Adrian Dale of ISLA, Allan Milligan of ISDA, and Georgina Jarrett, joined moderator Ffi
"Alan" not "Allan"

2024-07-19 08:23 UTC, chrisisla commented on docs/cdm-materials.md
> +On January 11th, 2023, FINADIUM sat down with Gabriel Columbro, the Executive Director at FINOS and General Manager of the Linux Foundation Europe, to discuss the exciting world of open source trends
"Gabriele" not "Gabriel"

2024-07-19 08:23 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/cdm-materials.md
> +At the keynote session of the 2022 Open Source in Finance Forum New York, a panel of industry leaders including Adrian Dale of ISLA, Allan Milligan of ISDA, and Georgina Jarrett, joined moderator Ffi
Alan again
Actually it's Ffion Acland - same will be wrong on the previous file too

2024-07-19 08:23 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/cdm-materials.md
> +The second half of the one-hour CDM presentation at the Open Source in Finance Forum (OSFF) in New York was dedicated to exploring the potential of Common Domain Model (CDM) in market infrastructure.
Eleonora Acuna

2024-07-19 08:23 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/cdm-materials.md
> +On January 11th, 2023, FINADIUM sat down with Gabriel Columbro, the Executive Director at FINOS and General Manager of the Linux Foundation Europe, to discuss the exciting world of open source trends
Gabriel

2024-07-19 08:49 UTC, Oblongs commented on docs/cdm-materials.md
> +### [Barclay's demonstration of interest rate swap processing using the Common Domain Model (CDM)](https://www.youtube.com/watch?v=LTWn_AWC4F8)
No quote in Barclays

2024-07-22 07:57 UTC, chrisisla approved these changes

2024-07-22 08:15 UTC, Oblongs approved these changes

2024-07-22 08:37 UTC, merged