Website Updates
finos/common-domain-model pull request #3091
Opened 2024-08-14 15:38 UTC by eteridvalishvili

CDM Website Update - August 

- [x] Meeting recording of Brian Lynns release schedule from Steering WG: https://resources.finos.org/category/projects-sigs/common-domain-model-cdm?projects-sigs=common-domain-model-cdm&c=cG9zdDo5OTE3MDQ%3D
- [x] Update “versioned??” Contribution.md page on the website to match the original
- [x] Update Governance.md 
    - [x] Section 4 language
    - [x] Section 6.0 include a link to the PowerPoint deck (as a PDF) shared by Brian Lynn

Add a Demo page 
    - [x] Add OTC Digital Demo: https://resources.finos.org/znglist/real-world-project-demos?c=cG9zdDo5OTE1NzA%3D
    - [x] Add Barcelona Hackathon Demo: https://www.youtube.com/watch?v=N9C2ZokZAV4
    - [x] Add ISDA DRR CDM Training Sessions Demo: https://www.youtube.com/watch?v=WaXR5uX-R8s
    - [x] Add How to get started session: https://resources.finos.org/category/projects-sigs/common-domain-model-cdm?projects-sigs=common-domain-model-cdm&c=cG9zdDo5OTE2Mjg%3D

2024-08-14 15:53 UTC, chrisisla requested changes

2024-08-14 15:53 UTC, chrisisla commented on docs/home.mdx
> +* [CDM Demos](/docs/cdm-demos.md)
think you need to remove the ".md" from the end for this to work properly

2024-08-14 15:53 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/contribution.md
> +**2.1.0 Any Participant may propose a Working Group.** Proposals for the formation of a new Working Group are made by completion of a new new CDM Working Group template, clearly stating the objective
"new new"

2024-08-14 15:53 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/home.mdx
> +* [CDM Demos](/docs/cdm-demos.md)
think you need to remove the .md suffix

2024-08-14 15:53 UTC, chrisisla commented on website/versioned_docs/version-5.13.0/cdm-demos.md
> +1. [Watch the demo from otc Digital entitled "Integrated digital assets marketplace with full lifecycle and automation using CDM](https://resources.finos.org/znglist/real-world-project-demos?c=cG9zdD
open quotes but no close quotes?

2024-08-14 15:53 UTC, chrisisla commented on docs/cdm-demos.md
> +1. [Watch the demo from otc Digital entitled "Integrated digital assets marketplace with full lifecycle and automation using CDM](https://resources.finos.org/znglist/real-world-project-demos?c=cG9zdD
open quotes no close quotes?

2024-08-15 08:40 UTC, dshoneisda approved these changes

2024-08-15 14:14 UTC, chrisisla approved these changes

2024-09-12 20:15 UTC, eteridvalishvili commented
Hi @finos/cdm-maintainers Could you please help me understand why this PR is failing? I can't seem to figure it out.

2024-09-27 19:48 UTC, eteridvalishvili commented
Hi @tomhealey-icma When you have a chance could I get your feedback on how I can fix this PR? Thank you in advance!

2024-10-18 16:12 UTC, eteridvalishvili commented
Hi @chrisisla and @dshoneisda Could you please review and merge this PR if everything looks good? Thank you in advance!

2024-10-23 09:08 UTC, dshoneisda approved these changes

2024-10-23 09:08 UTC, merged