Priyanka amarnani related party mapping processor[5xx]
finos/common-domain-model pull request #3259
Opened 2024-11-15 12:30 UTC by PayalKhanna

2024-11-15 12:31 UTC, PayalKhanna commented
@priyanka-amarnani can you please provide release notes for this attached as comment or .md file on this PR
Thanks

2024-11-15 12:33 UTC, PayalKhanna commented
@manel-martos can you review this please

2024-11-25 09:44 UTC, hugohills-regnosys requested changes
Need to map role from the FpML synonym not the CDM display name

2024-11-25 18:08 UTC, manel-martos approved these changes
Requested changes by @hugohills-regnosys and commited by @gopazoTH solve the ingestion issues observed on the previous contribution.

2024-11-26 10:54 UTC, PayalKhanna commented
@priyanka-amarnani @gopazoTH 
the Build is failing on python build for reason
```ERROR cdm-python/test/semantics/test_pydantic_simple.py - AttributeError: module 'cdm.product.template' has no attribute 'Product'
[2024-11-25T16:34:07.701Z] ERROR cdm-python/test/semantics/test_validation.py - AttributeError: module 'cdm.product.template' has no attribute 'Product'
```

could you please have a look at these please 

cc @manel-martos

2024-11-26 13:38 UTC, hugohills-regnosys commented
> @priyanka-amarnani @gopazoTH the Build is failing on python build for reason
> 
> ```
> [2024-11-25T16:34:07.701Z] ERROR cdm-python/test/semantics/test_validation.py - AttributeError: module 'cdm.product.template' has no attribute 'Product'
> ```
> 
> could you please have a look at these please
> 
> cc @manel-martos @hugohills-regnosys

This was due to the python versions used in the build/test script incrementing, and the tests not running with the latest version.  I have created a PR where the previous working versions are specified, see https://github.com/finos/common-domain-model/pull/3280

2024-11-27 13:47 UTC, manel-martos submitted a review, later dismissed

2025-01-17 09:37 UTC, dshoneisda approved these changes

2025-01-17 09:44 UTC, hugohills-regnosys submitted a review, later dismissed

2025-01-17 10:50 UTC, hugohills-regnosys approved these changes

2025-01-17 10:50 UTC, merged