Igallizugaro website review
finos/common-domain-model pull request #3300
Opened 2024-12-13 16:14 UTC by igallizugaro

Hi Eteri,
I would like to please create a pull request.

Thank you
Isabella

2024-12-16 09:21 UTC, igallizugaro commented
EasyCLA access granted

2024-12-16 16:44 UTC, dshoneisda commented
Summary of changes for easier review:


•	Separating pages into shorter, more focused pages to facilitate navigation and references. E.g., content previously contained in the governance page has been split into new a working groups page, change control guidelines, and major release scheduling guidelines pages.  The contribution page was broken down into a development approach page and versioning page – with links redirecting readers to the governance and design principles pages. 
•	New pages created are:
o	CDM organisation structure, design principles, development approach, documentation style guide, editing, maintainers, maintenance and release, change control guidelines, major release scheduling guidelines, versioning.
•	Home mdx renamed to Java distribution guidelines.
•	Linking pages and sections, allowing readers to clearly locate additional information. 
•	Fixing links – both broken links as all as well as functioning links to reference specific page sections. 
•	Ensuring all images referenced are correctly being displayed. 
•	Updating/removing repetitive text. (e.g. in Change control rules). Adding text for clarity (e.g. model descriptions in CDM overview page and in maintenance and release page).
•	Removing the duplicate information contained the GOVERNA	NCE, ROADMAP, README pages – linking to where the information was moved to.

2024-12-17 09:23 UTC, igallizugaro commented
> Hi @igallizugaro , When you have finished making your changes please let me know so that I can review 👍 There are lots of files so I will need a bit of time but it will be great to see the documentation updated! Thanks!

Hi Chris - I have finished and currently in the process of resolving errors flagged by the PR.

2025-01-09 15:22 UTC, dshoneisda submitted a review, later dismissed

2025-01-22 14:08 UTC, chrisisla requested changes
Some of my comments may not be valid as it could be that the documents are not present on the version of the website (e.g. Standardized IM calc, WG lists). Other than that there are just a few typos and duplicated words to sort out please 😃

2025-01-22 14:08 UTC, chrisisla commented on docs/maintenance-and-release.md
> +  * *(TODO:  insert a diagram of the promotion process)*
is this still a TODO, do we have a diagram for this?

2025-01-22 14:08 UTC, chrisisla commented on docs/working-groups.md
> +* [CDM Steering Working Group](CDM-Steering-WG.md) - quarterly
SWG is also monthly, not quarterly

2025-01-22 14:08 UTC, chrisisla commented on docs/working-groups.md
> +* [CDM Derivatives Product and Business Event Working Group](CDM-Derivatives-Product-and-Business-Event-WG.md) - bi-weekly
WG name has changed

2025-01-22 14:08 UTC, chrisisla commented on docs/working-groups.md
> +* [CDM Structured Products Working Group](CDM-Structured-Products-WG.md) - monthly
This WG is no more!

2025-01-27 16:37 UTC, igallizugaro commented on docs/contributions.md
> +This page will take you through how to contribute to the CDM, the necessary steps to take beforehand, editing and testing.
updated.

2025-01-27 16:42 UTC, igallizugaro commented on docs/maintainers.md
> +| Lyteck Lynhiavu      | ISDA           | OrgRep                                      | llynhiavu            |
done

2025-01-27 16:43 UTC, igallizugaro commented on docs/maintenance-and-release.md
> +Contributions are reviewed by the [Contribution Review Working Group](CDM-Contribution-Review-WG.md) and once approved, the [CDM Maintainers](maintainers.md) will release them following the the  guid
done

2025-01-27 16:46 UTC, igallizugaro commented on docs/maintenance-and-release.md
> +appropriate level of details with the [CDM Architecture](CDM-Technology-Architecture-WG.md) and [Review
done

2025-01-27 16:47 UTC, igallizugaro commented on docs/working-groups.md
> +* [CDM Steering Working Group](CDM-Steering-WG.md) - quarterly
done

2025-01-27 16:50 UTC, igallizugaro commented on docs/home.mdx
> +* [Use Cases](use-cases.md)
@dshoneisda please advise - thank you

2025-01-27 17:04 UTC, eacunaISDA approved these changes

2025-01-27 17:06 UTC, igallizugaro commented on docs/cdm-overview.md
> +For an overview of the Common Domain Model, a comparative analysis with FpML, an exploration of the CDM's historical development and events, as well as insights into its further applications, includi
added back in

2025-01-28 13:56 UTC, igallizugaro commented on docs/home.mdx
> +* [Use Cases](use-cases.md)
Comment from David - Unsure, priority is to have the PR out, this can be added later.

2025-01-28 15:09 UTC, eacunaISDA commented on docs/maintenance-and-release.md
> +  * *(TODO:  insert a diagram of the promotion process)*
@brianlynn2 please advise on diagram if such exists

2025-01-28 15:19 UTC, igallizugaro commented on docs/home.mdx
> +    - [Join the Derivatives Product and Business Event Working Group](CDM-Derivatives-Product-and-Business-Event-WG.md)
opened as issue

2025-01-28 15:19 UTC, igallizugaro commented on docs/working-groups.md
> +* [CDM Derivatives Product and Business Event Working Group](CDM-Derivatives-Product-and-Business-Event-WG.md) - bi-weekly
opened as issue

2025-01-28 15:20 UTC, igallizugaro commented on docs/working-groups.md
> +* [CDM Structured Products Working Group](CDM-Structured-Products-WG.md) - monthly
opened as issue

2025-01-28 15:21 UTC, igallizugaro commented on docs/maintenance-and-release.md
> +  * *(TODO:  insert a diagram of the promotion process)*
created issue

2025-01-28 15:37 UTC, igallizugaro commented on docs/home.mdx
> +* [Use Cases](use-cases.md)
created issue - https://github.com/finos/common-domain-model/issues/3347

2025-01-29 09:40 UTC, chrisisla commented
There are now 1246 files being updated in this PR, I'm not sure we can approve/merge this as is I'm afraid...

2025-01-31 09:24 UTC, chrisisla commented on docs/maintenance-and-release.md
> +appropriate level of details with the [CDM Architecture](CDM-Technology-Architecture-WG.md) and [Review
I think you changed the wrong "with" 😄 Sorry, my bad, I think the sentence should read:

"...the CDM Maintainer can recommend for the contribution to be presented **with** an appropriate level of **detail to** the..."

2025-01-31 09:25 UTC, chrisisla requested changes
Just that sentence in the maintenance-and-release.md file to correct and then we're all done 😄

2025-01-31 09:32 UTC, igallizugaro commented on docs/maintenance-and-release.md
> +appropriate level of details with the [CDM Architecture](CDM-Technology-Architecture-WG.md) and [Review
done

2025-01-31 09:34 UTC, chrisisla approved these changes
Perfect 👍

2025-02-11 14:40 UTC, closed without merging