Contribution 1: Extended Test Coverage for Examples Module - Release
finos/common-domain-model pull request #3304
Opened 2024-12-19 11:09 UTC by JayasriR

2024-12-19 11:10 UTC, JayasriR commented
@manel-martos Can you please let us know who can review this?

2025-01-13 13:14 UTC, PayalKhanna commented
@manel-martos Can you please let us know who can review this change and are we okay to merge this?

2025-01-17 11:51 UTC, PayalKhanna commented
@dshoneisda can you please review this

2025-01-17 12:57 UTC, chrisisla requested changes

2025-01-17 12:57 UTC, chrisisla commented on examples/src/test/java/org/finos/cdm/example/BusinessEventExecutionTest.java
> +     * Descripción: En derivados que implican tasas flotantes, el reset es el ajuste periódico de la tasa de referencia (como LIBOR o SOFR) a una nueva tasa vigente.
English por favor!

2025-01-17 12:57 UTC, chrisisla commented on examples/src/test/resources/logback-test.xml
> +    <logger name="org.finos.cdm.example" level="DEBUG" />
Can you expand a bit on the reason for this update please?

2025-01-28 16:42 UTC, PayalKhanna commented
@chrisisla @dshoneisda can you please review this
thanks

2025-02-03 09:48 UTC, PayalKhanna commented
@chrisisla @dshoneisda can you please review this
thanks

2025-02-13 11:38 UTC, chrisisla approved these changes

2025-02-13 13:00 UTC, merged